/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiaturistica.vista;

/**
 *
 * @author sandrojc
 */
public class AñadirElementosSitio extends javax.swing.JInternalFrame {

    /**
     * Creates new form AñadirElementosSitio
     */
    public AñadirElementosSitio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAñadirRuta = new javax.swing.JToggleButton();
        BtnSalir = new javax.swing.JButton();
        BtnAñadirRestaurante = new javax.swing.JButton();
        BtnAñadirHotel = new javax.swing.JButton();
        BtnAñadirTienda = new javax.swing.JButton();
        BtnAñadirTransporte = new javax.swing.JButton();

        setIconifiable(true);
        setResizable(true);

        BtnAñadirRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaturistica/imagenes/ruta-20x20.png"))); // NOI18N
        BtnAñadirRuta.setText("Ruta            ");
        BtnAñadirRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAñadirRutaMouseClicked(evt);
            }
        });
        BtnAñadirRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirRutaActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Droid Sans Mono", 0, 12)); // NOI18N
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaturistica/imagenes/cancelar-28x28.png"))); // NOI18N
        BtnSalir.setText("cancelar  ");
        BtnSalir.setBorderPainted(false);
        BtnSalir.setRequestFocusEnabled(false);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnAñadirRestaurante.setFont(new java.awt.Font("Droid Sans Mono", 0, 12)); // NOI18N
        BtnAñadirRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaturistica/imagenes/restaturant-20x20.png"))); // NOI18N
        BtnAñadirRestaurante.setText("Restaurante");
        BtnAñadirRestaurante.setBorderPainted(false);
        BtnAñadirRestaurante.setRequestFocusEnabled(false);
        BtnAñadirRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirRestauranteActionPerformed(evt);
            }
        });

        BtnAñadirHotel.setFont(new java.awt.Font("Droid Sans Mono", 0, 12)); // NOI18N
        BtnAñadirHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaturistica/imagenes/home-20x20.png"))); // NOI18N
        BtnAñadirHotel.setText("Hospedaje  ");
        BtnAñadirHotel.setBorderPainted(false);
        BtnAñadirHotel.setRequestFocusEnabled(false);
        BtnAñadirHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirHotelActionPerformed(evt);
            }
        });

        BtnAñadirTienda.setFont(new java.awt.Font("Droid Sans Mono", 0, 12)); // NOI18N
        BtnAñadirTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaturistica/imagenes/bolsa-20x20.png"))); // NOI18N
        BtnAñadirTienda.setText("Tienda     ");
        BtnAñadirTienda.setBorderPainted(false);
        BtnAñadirTienda.setRequestFocusEnabled(false);
        BtnAñadirTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirTiendaActionPerformed(evt);
            }
        });

        BtnAñadirTransporte.setFont(new java.awt.Font("Droid Sans Mono", 0, 12)); // NOI18N
        BtnAñadirTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaturistica/imagenes/bus-20x20.png"))); // NOI18N
        BtnAñadirTransporte.setText("Trasporte  ");
        BtnAñadirTransporte.setBorderPainted(false);
        BtnAñadirTransporte.setRequestFocusEnabled(false);
        BtnAñadirTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirTransporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAñadirRuta)
                    .addComponent(BtnAñadirRestaurante)
                    .addComponent(BtnAñadirHotel)
                    .addComponent(BtnAñadirTransporte)
                    .addComponent(BtnAñadirTienda)
                    .addComponent(BtnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnAñadirHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAñadirTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAñadirRestaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAñadirTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAñadirRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAñadirRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirRutaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnAñadirRutaActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnAñadirRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirRestauranteActionPerformed
        M4_RestaurantNuevo resNuevo = new M4_RestaurantNuevo();
        VentanaPrincipal.principal.add(resNuevo);
        resNuevo.toFront();
        resNuevo.setVisible(true);
    }//GEN-LAST:event_BtnAñadirRestauranteActionPerformed

    private void BtnAñadirHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirHotelActionPerformed
        // TODO add your handling code here:
        M2_HospedajeNuevo hosNuevo = new M2_HospedajeNuevo();
        VentanaPrincipal.principal.add(hosNuevo);
        hosNuevo.toFront();
        hosNuevo.setVisible(true);
    }//GEN-LAST:event_BtnAñadirHotelActionPerformed

    private void BtnAñadirTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirTiendaActionPerformed
        // TODO add your handling code here:
        M3_TiendaNuevo tieNuevo = new M3_TiendaNuevo();
        VentanaPrincipal.principal.add(tieNuevo);
        tieNuevo.toFront();
        tieNuevo.setVisible(true);
    }//GEN-LAST:event_BtnAñadirTiendaActionPerformed

    private void BtnAñadirTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirTransporteActionPerformed
        // TODO add your handling code here:
         M5_TransporteNuevo traNuevo = new M5_TransporteNuevo();
        VentanaPrincipal.principal.add(traNuevo);
        traNuevo.toFront();
        traNuevo.setVisible(true);
    }//GEN-LAST:event_BtnAñadirTransporteActionPerformed

    private void BtnAñadirRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAñadirRutaMouseClicked
        // TODO add your handling code here:
        M9_RutaNuevo rutNuevo = new M9_RutaNuevo();
        VentanaPrincipal.principal.add(rutNuevo);
        rutNuevo.toFront();
        rutNuevo.setVisible(true);
    }//GEN-LAST:event_BtnAñadirRutaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñadirHotel;
    private javax.swing.JButton BtnAñadirRestaurante;
    private javax.swing.JToggleButton BtnAñadirRuta;
    private javax.swing.JButton BtnAñadirTienda;
    private javax.swing.JButton BtnAñadirTransporte;
    private javax.swing.JButton BtnSalir;
    // End of variables declaration//GEN-END:variables
}
